package com.semasoft.niwapi.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTEST.
 */
public class Contest {

    private Integer contest_id;
    private String contest_media;
    private java.util.Date contest_date_loaded;
    private java.util.Date contest_date_solved;

    public Contest() {
    }

    public Contest(Integer contest_id, String contest_media, java.util.Date contest_date_loaded, java.util.Date contest_date_solved) {
        this.contest_id = contest_id;
        this.contest_media = contest_media;
        this.contest_date_loaded = contest_date_loaded;
        this.contest_date_solved = contest_date_solved;
    }

    public Integer getContest_id() {
        return contest_id;
    }

    public void setContest_id(Integer contest_id) {
        this.contest_id = contest_id;
    }

    public String getContest_media() {
        return contest_media;
    }

    public void setContest_media(String contest_media) {
        this.contest_media = contest_media;
    }

    public java.util.Date getContest_date_loaded() {
        return contest_date_loaded;
    }

    public void setContest_date_loaded(java.util.Date contest_date_loaded) {
        this.contest_date_loaded = contest_date_loaded;
    }

    public java.util.Date getContest_date_solved() {
        return contest_date_solved;
    }

    public void setContest_date_solved(java.util.Date contest_date_solved) {
        this.contest_date_solved = contest_date_solved;
    }

}
