package com.semasoft.niwapi.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.semasoft.niwapi.database.Contest;
import com.semasoft.niwapi.database.Trials;
import com.semasoft.niwapi.database.User;

import com.semasoft.niwapi.database.ContestDao;
import com.semasoft.niwapi.database.TrialsDao;
import com.semasoft.niwapi.database.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contestDaoConfig;
    private final DaoConfig trialsDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ContestDao contestDao;
    private final TrialsDao trialsDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contestDaoConfig = daoConfigMap.get(ContestDao.class).clone();
        contestDaoConfig.initIdentityScope(type);

        trialsDaoConfig = daoConfigMap.get(TrialsDao.class).clone();
        trialsDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        contestDao = new ContestDao(contestDaoConfig, this);
        trialsDao = new TrialsDao(trialsDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Contest.class, contestDao);
        registerDao(Trials.class, trialsDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        contestDaoConfig.getIdentityScope().clear();
        trialsDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public ContestDao getContestDao() {
        return contestDao;
    }

    public TrialsDao getTrialsDao() {
        return trialsDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
