package com.semasoft.niwapi.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRIALS.
 */
public class Trials {

    private Integer user_id;
    private Integer trials_id;
    private String user_attempt;
    private Integer contest_id;
    private java.util.Date trial_time;

    public Trials() {
    }

    public Trials(Integer user_id, Integer trials_id, String user_attempt, Integer contest_id, java.util.Date trial_time) {
        this.user_id = user_id;
        this.trials_id = trials_id;
        this.user_attempt = user_attempt;
        this.contest_id = contest_id;
        this.trial_time = trial_time;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getTrials_id() {
        return trials_id;
    }

    public void setTrials_id(Integer trials_id) {
        this.trials_id = trials_id;
    }

    public String getUser_attempt() {
        return user_attempt;
    }

    public void setUser_attempt(String user_attempt) {
        this.user_attempt = user_attempt;
    }

    public Integer getContest_id() {
        return contest_id;
    }

    public void setContest_id(Integer contest_id) {
        this.contest_id = contest_id;
    }

    public java.util.Date getTrial_time() {
        return trial_time;
    }

    public void setTrial_time(java.util.Date trial_time) {
        this.trial_time = trial_time;
    }

}
