package com.semasoft.niwapi.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Integer user_id;
    private String fb_token;
    private String user_name;
    private String user_phrase;
    private String user_mail;

    public User() {
    }

    public User(Integer user_id, String fb_token, String user_name, String user_phrase, String user_mail) {
        this.user_id = user_id;
        this.fb_token = fb_token;
        this.user_name = user_name;
        this.user_phrase = user_phrase;
        this.user_mail = user_mail;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getFb_token() {
        return fb_token;
    }

    public void setFb_token(String fb_token) {
        this.fb_token = fb_token;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getUser_phrase() {
        return user_phrase;
    }

    public void setUser_phrase(String user_phrase) {
        this.user_phrase = user_phrase;
    }

    public String getUser_mail() {
        return user_mail;
    }

    public void setUser_mail(String user_mail) {
        this.user_mail = user_mail;
    }

}
